In [11]:
import pandas as pd

In [12]:
df = pd.read_excel('/Users/vickylynnmauldin/Desktop/personal-repo/global-carbon-and-methane-emissions/Data/Methane_CleanData.xlsx')

In [13]:
df

,Country Code,Region,IncomeGroup,Country Name,1990,1991,1992,1993,1994,1995,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,AFE,NaN,NaN,Africa Eastern and Southern,320589.996671,321170.003211,326880.001700,330319.996810,339339.997625,347470.001196,...,503890.006164,508730.002934,494579.996178,496859.996045,501330.001080,509910.000766,515159.996608,518240.004519,519999.998191,525299.997816
1,AFG,South Asia,Low income,Afghanistan,6739.999771,7019.999981,7130.000114,7210.000038,7469.999790,7829.999924,...,15199.999809,15500.000000,15630.000114,15819.999695,16299.999237,15960.000038,15829.999924,15609.999657,15909.999847,16370.000839
2,AFW,NaN,NaN,Africa Western and Central,225169.999979,244579.997182,253969.999358,259030.004174,264790.000498,263709.999636,...,300400.002398,308019.998342,310789.995939,315619.999558,323400.005162,330440.002084,343199.999519,349769.998014,359360.009015,366629.998177
3,AGO,Sub-Saharan Africa,Lower middle income,Angola,21219.999313,21489.999771,21950.000763,22579.999924,23479.999542,25229.999542,...,36900.001526,36639.999390,35770.000458,35759.998322,34900.001526,37110.000610,37430.000305,37619.998932,34000.000000,35090.000153
4,ALB,Europe & Central Asia,Upper middle income,Albania,3539.999962,3500.000000,3410.000086,3490.000010,4079.999924,4079.999924,...,3029.999971,3019.999981,3059.999943,3059.999943,3089.999914,3109.999895,3089.999914,3049.999952,3009.999990,2849.999905
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,WSM,East Asia & Pacific,Lower middle income,Samoa,209.999993,209.999993,200.000003,209.999993,239.999995,239.999995,...,270.000011,280.000001,280.000001,280.000001,289.999992,300.000012,310.000002,300.000012,310.000002,310.000002
235,YEM,Middle East & North Africa,Low income,"Yemen, Rep.",8890.000343,8899.999619,8750.000000,10659.999847,14729.999542,14659.999847,...,23049.999237,22329.999924,19799.999237,22360.000610,20950.000763,12260.000229,9350.000381,10140.000343,10619.999886,10609.999657
236,ZAF,Sub-Saharan Africa,Upper middle income,South Africa,63189.998627,64120.002747,63750.000000,65739.997864,66739.997864,67300.003052,...,77260.002136,77260.002136,79209.999084,79029.998779,79919.998169,79160.003662,78739.997864,80110.000610,79839.996338,80129.997253
237,ZMB,Sub-Saharan Africa,Low income,Zambia,12029.999733,12189.999580,12270.000458,12180.000305,12060.000420,11979.999542,...,14409.999847,13869.999886,15460.000038,15729.999542,15590.000153,15819.999695,15640.000343,15020.000458,15250.000000,15619.999886
238,ZWE,Sub-Saharan Africa,Lower middle income,Zimbabwe,9609.999657,8720.000267,9329.999924,7800.000191,8470.000267,8869.999886,...,12270.000458,12640.000343,12460.000038,12340.000153,11369.999886,12260.000229,11869.999886,12060.000420,12340.000153,12550.000191

In [14]:
nan_values = df[df['Region'].isna()]
nan_values

,Country Code,Region,IncomeGroup,Country Name,1990,1991,1992,1993,1994,1995,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,AFE,NaN,NaN,Africa Eastern and Southern,3.205900e+05,3.211700e+05,3.268800e+05,3.303200e+05,3.393400e+05,3.474700e+05,...,5.038900e+05,5.087300e+05,4.945800e+05,4.968600e+05,5.013300e+05,5.099100e+05,5.151600e+05,5.182400e+05,5.200000e+05,5.253000e+05
2,AFW,NaN,NaN,Africa Western and Central,2.251700e+05,2.445800e+05,2.539700e+05,2.590300e+05,2.647900e+05,2.637100e+05,...,3.004000e+05,3.080200e+05,3.107900e+05,3.156200e+05,3.234000e+05,3.304400e+05,3.432000e+05,3.497700e+05,3.593600e+05,3.666300e+05
6,ARB,NaN,NaN,Arab World,4.073500e+05,3.945100e+05,4.093100e+05,4.350700e+05,4.578500e+05,4.732300e+05,...,6.473600e+05,6.293900e+05,6.842200e+05,6.691400e+05,6.607500e+05,6.711700e+05,6.960800e+05,7.157600e+05,7.334300e+05,7.474700e+05
33,CEB,NaN,NaN,Central Europe and the Baltics,1.550600e+05,1.472300e+05,1.395600e+05,1.314800e+05,1.240400e+05,1.205400e+05,...,9.843000e+04,9.534000e+04,9.423000e+04,9.279000e+04,9.150000e+04,9.110000e+04,8.950000e+04,8.972000e+04,8.866000e+04,8.798000e+04
45,CSS,NaN,NaN,Caribbean small states,2.037000e+04,2.084000e+04,2.111000e+04,1.965000e+04,1.834000e+04,1.721000e+04,...,1.715000e+04,1.726000e+04,1.732000e+04,1.755000e+04,1.763000e+04,1.723000e+04,1.613000e+04,1.635000e+04,1.646000e+04,1.683000e+04
55,EAP,NaN,NaN,East Asia & Pacific (excluding high income),1.292740e+06,1.312420e+06,1.330640e+06,1.347950e+06,1.379870e+06,1.434330e+06,...,1.730270e+06,1.778920e+06,1.781710e+06,1.810710e+06,1.830560e+06,1.828580e+06,1.794660e+06,1.816420e+06,1.847660e+06,1.862750e+06
56,EAR,NaN,NaN,Early-demographic dividend,2.140190e+06,2.201230e+06,2.208830e+06,2.260260e+06,2.290240e+06,2.348270e+06,...,2.797250e+06,2.800840e+06,2.855790e+06,2.844060e+06,2.863670e+06,2.874470e+06,2.919070e+06,2.962090e+06,2.979020e+06,2.960800e+06
57,EAS,NaN,NaN,East Asia & Pacific,1.528850e+06,1.548270e+06,1.564870e+06,1.581040e+06,1.615400e+06,1.668600e+06,...,1.938350e+06,2.036030e+06,2.037920e+06,2.029320e+06,2.060710e+06,2.053340e+06,2.003120e+06,2.047500e+06,2.077500e+06,2.077260e+06
58,ECA,NaN,NaN,Europe & Central Asia (excluding high income),1.083880e+06,1.045600e+06,9.648200e+05,9.343900e+05,8.826300e+05,8.507400e+05,...,9.045000e+05,9.275800e+05,9.290700e+05,9.361700e+05,9.364800e+05,9.384500e+05,9.546500e+05,9.757900e+05,1.012230e+06,1.029870e+06
59,ECS,NaN,NaN,Europe & Central Asia,1.717730e+06,1.669960e+06,1.576360e+06,1.537430e+06,1.480490e+06,1.444560e+06,...,1.376460e+06,1.384140e+06,1.380640e+06,1.378750e+06,1.370690e+06,1.372640e+06,1.387010e+06,1.406330e+06,1.434880e+06,1.448460e+06
62,EMU,NaN,NaN,Euro area,3.790500e+05,3.754700e+05,3.695400e+05,3.642300e+05,3.606400e+05,3.589200e+05,...,3.066900e+05,2.985800e+05,2.963300e+05,2.927100e+05,2.880300e+05,2.892500e+05,2.873200e+05,2.856100e+05,2.794700e+05,2.771100e+05
67,EUU,NaN,NaN,European Union,5.286000e+05,5.176900e+05,5.040800e+05,4.931300e+05,4.843300e+05,4.798500e+05,...,4.063500e+05,3.949800e+05,3.918300e+05,3.863900e+05,3.805100e+05,3.811200e+05,3.775400e+05,3.760500e+05,3.687400e+05,3.653800e+05
68,FCS,NaN,NaN,Fragile and conflict affected situations,6.859200e+05,6.833300e+05,6.981000e+05,7.142400e+05,7.412500e+05,7.638900e+05,...,9.844300e+05,9.520900e+05,9.951800e+05,9.895600e+05,9.843200e+05,9.937800e+05,1.006870e+06,1.021200e+06,1.027900e+06,1.024650e+06
85,HIC,NaN,NaN,High income,1.743330e+06,1.749420e+06,1.751380e+06,1.741370e+06,1.753060e+06,1.751700e+06,...,1.643860e+06,1.700440e+06,1.714630e+06,1.678220e+06,1.707710e+06,1.709900e+06,1.685350e+06,1.723150e+06,1.763770e+06,1.780370e+06
87,HPC,NaN,NaN,Heavily indebted poor countries (HIPC),3.121100e+05,3.253600e+05,3.348600e+05,3.394500e+05,3.474100e+05,3.532100e+05,...,5.107700e+05,5.199000e+05,5.299500e+05,5.443300e+05,5.539100e+05,5.679500e+05,5.809600e+05,5.866600e+05,5.986900e+05,6.083700e+05
91,IBD,NaN,NaN,IBRD only,4.079030e+06,4.063910e+06,4.019480e+06,4.042540e+06,4.058250e+06,4.125070e+06,...,4.897970e+06,4.947520e+06,5.013750e+06,5.023990e+06,5.061740e+06,5.088240e+06,5.109540e+06,5.169850e+06,5.224840e+06,5.239280e+06
92,IBT,NaN,NaN,IDA & IBRD total,4.853430e+06,4.863570e+06,4.839460e+06,4.880200e+06,4.918300e+06,4.997080e+06,...,6.049420e+06,6.113340e+06,6.166070e+06,6.192870e+06,6.244800e+06,6.283690e+06,6.328250e+06,6.408310e+06,6.491140e+06,6.527110e+06
93,IDA,NaN,NaN,IDA total,7.744000e+05,7.996600e+05,8.199800e+05,8.376600e+05,8.600500e+05,8.720100e+05,...,1.151450e+06,1.165820e+06,1.152320e+06,1.168880e+06,1.183060e+06,1.195450e+06,1.218710e+06,1.238460e+06,1.266300e+06,1.287830e+06
94,IDB,NaN,NaN,IDA blend,2.858200e+05,2.979200e+05,3.018300e+05,3.056400e+05,3.118000e+05,3.106600e+05,...,3.714700e+05,3.826700e+05,3.864800e+05,3.901800e+05,3.942100e+05,4.003200e+05,4.117300e+05,4.185700e+05,4.330700e+05,4.456100e+05
96,IDX,NaN,NaN,IDA only,4.885800e+05,5.017400e+05,5.181500e+05,5.320200e+05,5.482500e+05,5.613500e+05,...,7.799800e+05,7.831500e+05,7.658400e+05,7.787000e+05,7.888500e+05,7.951300e+05,8.069800e+05,8.198900e+05,8.332300e+05,8.422200e+05
115,LAC,NaN,NaN,Latin America & Caribbean (excluding high income),6.671900e+05,6.761000e+05,6.877200e+05,6.987200e+05,7.120400e+05,7.205900e+05,...,9.035900e+05,9.062300e+05,9.129400e+05,9.095100e+05,9.276100e+05,9.413700e+05,9.468100e+05,9.480700e+05,9.466200e+05,9.610800e+05
121,LCN,NaN,NaN,Latin America & Caribbean,8.403800e+05,8.611000e+05,8.747500e+05,8.902600e+05,9.072800e+05,9.286600e+05,...,1.128490e+06,1.133130e+06,1.153600e+06,1.151770e+06,1.167710e+06,1.174510e+06,1.169870e+06,1.152010e+06,1.131920e+06,1.127470e+06
122,LDC,NaN,NaN,Least developed countries: UN classification,4.459000e+05,4.523200e+05,4.631300e+05,4.739700e+05,4.883100e+05,5.022500e+05,...,7.457900e+05,7.494700e+05,7.406900e+05,7.577700e+05,7.678900e+05,7.760000e+05,7.876800e+05,7.989700e+05,8.089200e+05,8.166700e+05
123,LIC,NaN,NaN,Low income,2.994600e+05,3.092800e+05,3.187300e+05,3.255400e+05,3.366600e+05,3.413200e+05,...,4.957400e+05,4.956500e+05,4.772100e+05,4.839200e+05,4.910100e+05,4.916100e+05,4.998100e+05,5.075900e+05,5.176800e+05,5.226800e+05
126,LMC,NaN,NaN,Lower middle income,1.729950e+06,1.766680e+06,1.787090e+06,1.813680e+06,1.836990e+06,1.871370e+06,...,2.192770e+06,2.217130e+06,2.217790e+06,2.229670e+06,2.256970e+06,2.279320e+06,2.332710e+06,2.369630e+06,2.395840e+06,2.392640e+06
127,LMY,NaN,NaN,Low & middle income,4.641780e+06,4.643140e+06,4.620320e+06,4.657210e+06,4.692170e+06,4.758240e+06,...,5.800420e+06,5.865780e+06,5.904980e+06,5.930460e+06,5.985320e+06,6.030910e+06,6.086740e+06,6.185690e+06,6.287690e+06,6.342990e+06
129,LTE,NaN,NaN,Late-demographic dividend,2.280730e+06,2.262480e+06,2.234630e+06,2.217580e+06,2.215000e+06,2.236860e+06,...,2.721400e+06,2.783270e+06,2.791010e+06,2.823020e+06,2.841190e+06,2.852020e+06,2.834080e+06,2.863060e+06,2.917740e+06,2.957550e+06
137,MEA,NaN,NaN,Middle East & North Africa,4.756900e+05,4.709000e+05,4.900700e+05,5.187700e+05,5.403300e+05,5.581300e+05,...,7.788500e+05,7.599700e+05,8.059500e+05,7.867000e+05,7.850300e+05,8.004300e+05,8.532600e+05,8.850400e+05,9.025800e+05,8.904700e+05
140,MIC,NaN,NaN,Middle income,4.342320e+06,4.333860e+06,4.301590e+06,4.331670e+06,4.355510e+06,4.416920e+06,...,5.304680e+06,5.370130e+06,5.427770e+06,5.446540e+06,5.494310e+06,5.539300e+06,5.586930e+06,5.678100e+06,5.770010e+06,5.820310e+06
145,MNA,NaN,NaN,Middle East & North Africa (excluding high inc...,3.624600e+05,3.461800e+05,3.554800e+05,3.785300e+05,3.988600e+05,4.133300e+05,...,5.774100e+05,5.421000e+05,5.792400e+05,5.542500e+05,5.514000e+05,5.595500e+05,6.026100e+05,6.375100e+05,6.496500e+05,6.366500e+05
153,NAC,NaN,NaN,North America,7.189300e+05,7.221500e+05,7.275000e+05,7.220700e+05,7.361000e+05,7.368900e+05,...,7.133000e+05,7.193400e+05,7.307300e+05,7.359800e+05,7.616500e+05,7.627000e+05,7.468000e+05,7.670500e+05,8.111300e+05,8.462100e+05
163,OED,NaN,NaN,OECD members,1.760550e+06,1.757370e+06,1.752860e+06,1.749110e+06,1.762730e+06,1.760430e+06,...,1.629200e+06,1.673940e+06,1.678400e+06,1.630000e+06,1.668970e+06,1.667930e+06,1.636940e+06,1.678230e+06,1.720980e+06,1.742420e+06
165,OSS,NaN,NaN,Other small states,3.854000e+04,3.998000e+04,4.107000e+04,4.198000e+04,4.312000e+04,4.458000e+04,...,7.810000e+04,8.360000e+04,7.978000e+04,7.658000e+04,7.752000e+04,7.698000e+04,7.679000e+04,7.737000e+04,7.561000e+04,7.482000e+04
173,PRE,NaN,NaN,Pre-demographic dividend,4.653500e+05,4.472000e+05,4.647200e+05,4.809800e+05,4.962800e+05,5.019100e+05,...,7.041300e+05,7.204400e+05,7.201400e+05,7.321100e+05,7.494100e+05,7.757000e+05,8.051000e+05,8.110200e+05,8.260400e+05,8.422100e+05
177,PSS,NaN,NaN,Pacific island small states,1.590000e+03,1.640000e+03,1.670000e+03,1.740000e+03,1.820000e+03,1.880000e+03,...,2.030000e+03,2.070000e+03,2.090000e+03,2.110000e+03,1.720000e+03,1.760000e+03,1.780000e+03,1.820000e+03,1.840000e+03,1.900000e+03
178,PST,NaN,NaN,Post-demographic dividend,1.630640e+06,1.624120e+06,1.606840e+06,1.588170e+06,1.596650e+06,1.588860e+06,...,1.397160e+06,1.438850e+06,1.443770e+06,1.403000e+06,1.430640e+06,1.424240e+06,1.389670e+06,1.429510e+06,1.466590e+06,1.481800e+06
183,SAS,NaN,NaN,South Asia,6.898100e+05,6.971500e+05,7.008700e+05,7.083300e+05,7.147000e+05,7.281300e+05,...,8.804400e+05,8.942800e+05,8.967400e+05,9.074300e+05,9.146300e+05,9.227000e+05,9.297400e+05,9.399800e+05,9.522600e+05,9.608000e+05
193,SSA,NaN,NaN,Sub-Saharan Africa (excluding high income),5.457000e+05,5.656900e+05,5.807900e+05,5.892900e+05,6.040700e+05,6.111200e+05,...,8.042100e+05,8.166700e+05,8.052800e+05,8.123900e+05,8.246400e+05,8.402600e+05,8.582700e+05,8.679200e+05,8.792700e+05,8.918400e+05
195,SSF,NaN,NaN,Sub-Saharan Africa,5.457600e+05,5.657500e+05,5.808500e+05,5.893500e+05,6.041300e+05,6.111800e+05,...,8.042900e+05,8.167500e+05,8.053700e+05,8.124800e+05,8.247300e+05,8.403500e+05,8.583600e+05,8.680100e+05,8.793600e+05,8.919300e+05
196,SST,NaN,NaN,Small states,6.050000e+04,6.246000e+04,6.385000e+04,6.337000e+04,6.328000e+04,6.367000e+04,...,9.728000e+04,1.029300e+05,9.919000e+04,9.624000e+04,9.687000e+04,9.597000e+04,9.470000e+04,9.554000e+04,9.391000e+04,9.355000e+04
206,TEA,NaN,NaN,East Asia & Pacific (IDA & IBRD countries),1.266110e+06,1.287290e+06,1.306860e+06,1.325520e+06,1.358770e+06,1.414660e+06,...,1.713560e+06,1.762050e+06,1.764600e+06,1.793560e+06,1.813290e+06,1.811370e+06,1.777310e+06,1.798480e+06,1.829710e+06,1.844670e+06
207,TEC,NaN,NaN,Europe & Central Asia (IDA & IBRD countries),1.163780e+06,1.120590e+06,1.035140e+06,1.001780e+06,9.485200e+05,9.148900e+05,...,9.596300e+05,9.797700e+05,9.812500e+05,9.881500e+05,9.878000e+05,9.894900e+05,1.004740e+06,1.026280e+06,1.062240e+06,1.079310e+06
212,TLA,NaN,NaN,Latin America & the Caribbean (IDA & IBRD coun...,8.255100e+05,8.466100e+05,8.602600e+05,8.766900e+05,8.933200e+05,9.148900e+05,...,1.114090e+06,1.118390e+06,1.138870e+06,1.137000e+06,1.152950e+06,1.160230e+06,1.155490e+06,1.138050e+06,1.117920e+06,1.113750e+06
214,TMN,NaN,NaN,Middle East & North Africa (IDA & IBRD countries),3.624600e+05,3.461800e+05,3.554800e+05,3.785300e+05,3.988600e+05,4.133300e+05,...,5.774100e+05,5.421000e+05,5.792400e+05,5.542500e+05,5.514000e+05,5.595500e+05,6.026100e+05,6.375100e+05,6.496500e+05,6.366500e+05
216,TSA,NaN,NaN,South Asia (IDA & IBRD),6.898100e+05,6.971500e+05,7.008700e+05,7.083300e+05,7.147000e+05,7.281300e+05,...,8.804400e+05,8.942800e+05,8.967400e+05,9.074300e+05,9.146300e+05,9.227000e+05,9.297400e+05,9.399800e+05,9.522600e+05,9.608000e+05
217,TSS,NaN,NaN,Sub-Saharan Africa (IDA & IBRD countries),5.457600e+05,5.657500e+05,5.808500e+05,5.893500e+05,6.041300e+05,6.111800e+05,...,8.042900e+05,8.167500e+05,8.053700e+05,8.124800e+05,8.247300e+05,8.403500e+05,8.583600e+05,8.680100e+05,8.793600e+05,8.919300e+05
225,UMC,NaN,NaN,Upper middle income,2.612370e+06,2.567180e+06,2.514500e+06,2.517990e+06,2.518520e+06,2.545550e+06,...,3.111910e+06,3.153000e+06,3.209980e+06,3.216870e+06,3.237340e+06,3.259980e+06,3.254220e+06,3.308470e+06,3.374170e+06,3.427670e+06
233,WLD,NaN,NaN,World,6.517150e+06,6.535280e+06,6.515270e+06,6.547250e+06,6.598430e+06,6.676150e+06,...,7.620180e+06,7.743640e+06,7.810950e+06,7.802430e+06,7.885150e+06,7.926670e+06,7.948160e+06,8.065920e+06,8.189630e+06,8.242600e+06

In [15]:
#loop through NaN df to get index 
index_list = []
for idx in nan_values.index:
    index_list.append(idx)

# print the resulting list of index values
print(index_list)

[0, 2, 6, 33, 45, 55, 56, 57, 58, 59, 62, 67, 68, 85, 87, 91, 92, 93, 94, 96, 115, 121, 122, 123, 126, 127, 129, 137, 140, 145, 153, 163, 165, 173, 177, 178, 183, 193, 195, 196, 206, 207, 212, 214, 216, 217, 225, 233]

In [16]:
#remove index column and set index to country code
countries = df.set_index('Country Code')
countries

,Region,IncomeGroup,Country Name,1990,1991,1992,1993,1994,1995,1996,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Country Code,,,,,,,,,,,,,,,,,,,,,
AFE,NaN,NaN,Africa Eastern and Southern,320589.996671,321170.003211,326880.001700,330319.996810,339339.997625,347470.001196,351490.002086,...,503890.006164,508730.002934,494579.996178,496859.996045,501330.001080,509910.000766,515159.996608,518240.004519,519999.998191,525299.997816
AFG,South Asia,Low income,Afghanistan,6739.999771,7019.999981,7130.000114,7210.000038,7469.999790,7829.999924,8670.000076,...,15199.999809,15500.000000,15630.000114,15819.999695,16299.999237,15960.000038,15829.999924,15609.999657,15909.999847,16370.000839
AFW,NaN,NaN,Africa Western and Central,225169.999979,244579.997182,253969.999358,259030.004174,264790.000498,263709.999636,269409.994841,...,300400.002398,308019.998342,310789.995939,315619.999558,323400.005162,330440.002084,343199.999519,349769.998014,359360.009015,366629.998177
AGO,Sub-Saharan Africa,Lower middle income,Angola,21219.999313,21489.999771,21950.000763,22579.999924,23479.999542,25229.999542,25389.999390,...,36900.001526,36639.999390,35770.000458,35759.998322,34900.001526,37110.000610,37430.000305,37619.998932,34000.000000,35090.000153
ALB,Europe & Central Asia,Upper middle income,Albania,3539.999962,3500.000000,3410.000086,3490.000010,4079.999924,4079.999924,3910.000086,...,3029.999971,3019.999981,3059.999943,3059.999943,3089.999914,3109.999895,3089.999914,3049.999952,3009.999990,2849.999905
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WSM,East Asia & Pacific,Lower middle income,Samoa,209.999993,209.999993,200.000003,209.999993,239.999995,239.999995,239.999995,...,270.000011,280.000001,280.000001,280.000001,289.999992,300.000012,310.000002,300.000012,310.000002,310.000002
YEM,Middle East & North Africa,Low income,"Yemen, Rep.",8890.000343,8899.999619,8750.000000,10659.999847,14729.999542,14659.999847,15029.999733,...,23049.999237,22329.999924,19799.999237,22360.000610,20950.000763,12260.000229,9350.000381,10140.000343,10619.999886,10609.999657
ZAF,Sub-Saharan Africa,Upper middle income,South Africa,63189.998627,64120.002747,63750.000000,65739.997864,66739.997864,67300.003052,66900.001526,...,77260.002136,77260.002136,79209.999084,79029.998779,79919.998169,79160.003662,78739.997864,80110.000610,79839.996338,80129.997253
ZMB,Sub-Saharan Africa,Low income,Zambia,12029.999733,12189.999580,12270.000458,12180.000305,12060.000420,11979.999542,11250.000000,...,14409.999847,13869.999886,15460.000038,15729.999542,15590.000153,15819.999695,15640.000343,15020.000458,15250.000000,15619.999886
ZWE,Sub-Saharan Africa,Lower middle income,Zimbabwe,9609.999657,8720.000267,9329.999924,7800.000191,8470.000267,8869.999886,10340.000153,...,12270.000458,12640.000343,12460.000038,12340.000153,11369.999886,12260.000229,11869.999886,12060.000420,12340.000153,12550.000191

In [17]:
countries_final = countries.drop(countries.index [[0, 2, 6, 33, 45, 55, 56, 57, 58, 59, 62, 67, 68, 85, 87, 91, 92, 93, 94, 96, 115, 121, 122, 123, 126, 127, 129, 137, 140, 145, 153, 163, 165, 173, 177, 178, 183, 193, 195, 196, 206, 207, 212, 214, 216, 217, 225, 233]])
countries_final

,Region,IncomeGroup,Country Name,1990,1991,1992,1993,1994,1995,1996,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Country Code,,,,,,,,,,,,,,,,,,,,,
AFG,South Asia,Low income,Afghanistan,6739.999771,7019.999981,7130.000114,7210.000038,7469.999790,7829.999924,8670.000076,...,15199.999809,15500.000000,15630.000114,15819.999695,16299.999237,15960.000038,15829.999924,15609.999657,15909.999847,16370.000839
AGO,Sub-Saharan Africa,Lower middle income,Angola,21219.999313,21489.999771,21950.000763,22579.999924,23479.999542,25229.999542,25389.999390,...,36900.001526,36639.999390,35770.000458,35759.998322,34900.001526,37110.000610,37430.000305,37619.998932,34000.000000,35090.000153
ALB,Europe & Central Asia,Upper middle income,Albania,3539.999962,3500.000000,3410.000086,3490.000010,4079.999924,4079.999924,3910.000086,...,3029.999971,3019.999981,3059.999943,3059.999943,3089.999914,3109.999895,3089.999914,3049.999952,3009.999990,2849.999905
AND,Europe & Central Asia,High income,Andorra,20.000000,20.000000,20.000000,29.999999,29.999999,29.999999,29.999999,...,50.000001,50.000001,50.000001,50.000001,50.000001,50.000001,50.000001,50.000001,50.000001,50.000001
ARE,Middle East & North Africa,High income,United Arab Emirates,16459.999084,17870.000839,17809.999466,18280.000687,19670.000076,20370.000839,21290.000916,...,35720.001221,38360.000610,40310.001373,42439.998627,42869.998932,45709.999084,47360.000610,46900.001526,47459.999084,49799.999237
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WSM,East Asia & Pacific,Lower middle income,Samoa,209.999993,209.999993,200.000003,209.999993,239.999995,239.999995,239.999995,...,270.000011,280.000001,280.000001,280.000001,289.999992,300.000012,310.000002,300.000012,310.000002,310.000002
YEM,Middle East & North Africa,Low income,"Yemen, Rep.",8890.000343,8899.999619,8750.000000,10659.999847,14729.999542,14659.999847,15029.999733,...,23049.999237,22329.999924,19799.999237,22360.000610,20950.000763,12260.000229,9350.000381,10140.000343,10619.999886,10609.999657
ZAF,Sub-Saharan Africa,Upper middle income,South Africa,63189.998627,64120.002747,63750.000000,65739.997864,66739.997864,67300.003052,66900.001526,...,77260.002136,77260.002136,79209.999084,79029.998779,79919.998169,79160.003662,78739.997864,80110.000610,79839.996338,80129.997253
ZMB,Sub-Saharan Africa,Low income,Zambia,12029.999733,12189.999580,12270.000458,12180.000305,12060.000420,11979.999542,11250.000000,...,14409.999847,13869.999886,15460.000038,15729.999542,15590.000153,15819.999695,15640.000343,15020.000458,15250.000000,15619.999886
ZWE,Sub-Saharan Africa,Lower middle income,Zimbabwe,9609.999657,8720.000267,9329.999924,7800.000191,8470.000267,8869.999886,10340.000153,...,12270.000458,12640.000343,12460.000038,12340.000153,11369.999886,12260.000229,11869.999886,12060.000420,12340.000153,12550.000191

In [18]:
#export as excel 
countries_final.to_excel('/Users/vickylynnmauldin/Desktop/personal-repo/global-carbon-and-methane-emissions/Data/Methane_justcountries.xlsx')